"""Unify agent context (instructions + memory + skills) across Claude / Codex /
Copilot, with a single canonical source and symlinks for the rest.

Canonical layout (see also the plan and CLAUDE.md):

    AGENTS.md                          canonical instructions (root + per project)
    CLAUDE.md            -> AGENTS.md   symlink (Claude Code)
    .github/copilot-instructions.md -> ../AGENTS.md
    .agents/memory/                    canonical memory (committed); MEMORY.md index
    ~/.claude/projects/<slug>/memory -> <repo>/.agents/memory   (built-in feature → repo)

Everything here is idempotent and safe to re-run. The same engine backs both
``lab agents sync`` and the server's ``POST /api/agents/sync``.
"""
from __future__ import annotations

import os
import shutil
from pathlib import Path

from lab import paths

# First line of every file we generate, so re-runs never clobber hand edits.
GENERATED_MARK = "<!-- generated by `lab agents sync` — edit the canonical source instead -->"

_MEMORY_MARKER = "## Memory (repo-local — read at session start)"

_MEMORY_SECTION = f"""

{_MEMORY_MARKER}

This repo carries its **own agent memory** under `.agents/memory/` — committed and
pushed with the code, **never** in `~/.claude`, `~/.codex`, or any tool's install
dir. This applies to every agent (Claude Code, Codex, Copilot):

- **At the start of a session**, read `.agents/memory/MEMORY.md` (the index) and
  load the linked files relevant to your task.
- **When you learn a durable fact** (a preference, a project constraint, a
  hard-won gotcha), append it as one file under `.agents/memory/` and add a
  one-line pointer to `MEMORY.md`. One fact per file.
- **Commit and push** memory changes along with your other work, so they travel
  with the repo.
- Monorepo-level memory lives at the root `.agents/memory/` (committed to the
  productivity repo); per-project memory lives at `projects/<id>/.agents/memory/`
  and travels with that project folder. Use whichever matches the scope of the fact.

Claude Code's built-in memory directory is symlinked into `.agents/memory/`, so
its automatic memory writes land in the repo too — do not write memory anywhere
under `~/.claude`.
"""

_MEMORY_INDEX_STUB = (
    "# Memory index\n\n"
    "<!-- One line per memory: `- [Title](file.md) — hook`. "
    "See AGENTS.md → Memory. -->\n"
)


def _rel(p: Path, root: Path) -> str:
    try:
        return str(p.relative_to(root))
    except ValueError:
        # Outside the repo (e.g. ~/.claude) — show ~-relative for readability.
        try:
            return "~/" + str(p.relative_to(Path.home()))
        except ValueError:
            return str(p)


def _ensure_symlink(link: Path, target: Path, *, relative: bool,
                    actions: list[str], root: Path, dry_run: bool) -> None:
    """Make ``link`` a symlink to ``target``. Idempotent; never clobbers a real file."""
    want = os.path.relpath(target, link.parent) if relative else str(target)
    if link.is_symlink():
        try:
            if link.resolve() == target.resolve():
                return  # already correct
        except OSError:
            pass
        if not dry_run:
            link.unlink()
            link.symlink_to(want)
        actions.append(f"repoint {_rel(link, root)} → {want}")
        return
    if link.exists():
        actions.append(f"skip {_rel(link, root)}: a real file is in the way (not a symlink)")
        return
    if not dry_run:
        link.parent.mkdir(parents=True, exist_ok=True)
        link.symlink_to(want)
    actions.append(f"link {_rel(link, root)} → {want}")


def _migrate_instructions(pdir: Path, *, create_stub: bool,
                          actions: list[str], root: Path, dry_run: bool) -> bool:
    """Establish ``<pdir>/AGENTS.md`` as canonical + ``CLAUDE.md`` symlink.

    Returns True if an AGENTS.md exists (or was created) afterwards.
    """
    agents_md = pdir / "AGENTS.md"
    claude_md = pdir / "CLAUDE.md"
    just_freed = False  # CLAUDE.md was (or would be) moved out of the way
    if not agents_md.exists():
        if claude_md.is_file() and not claude_md.is_symlink():
            if not dry_run:
                shutil.move(str(claude_md), str(agents_md))
            actions.append(f"move {_rel(claude_md, root)} → {_rel(agents_md, root)}")
            just_freed = True
        elif create_stub:
            if not dry_run:
                agents_md.write_text(
                    f"# {pdir.name}\n\nInstructions for agents working in this repo.\n",
                    encoding="utf-8",
                )
            actions.append(f"create {_rel(agents_md, root)}")
        else:
            return False  # nothing to migrate for this project
    # On a dry run the move above didn't actually happen, so CLAUDE.md is still a
    # real file — report the symlink we *would* create instead of a false "skip".
    if dry_run and just_freed and claude_md.is_file() and not claude_md.is_symlink():
        actions.append(f"link {_rel(claude_md, root)} → AGENTS.md")
        return True
    _ensure_symlink(claude_md, agents_md, relative=True,
                    actions=actions, root=root, dry_run=dry_run)
    return True


def _ensure_memory_section(agents_md: Path, *, actions: list[str],
                           root: Path, dry_run: bool) -> None:
    """Append the repo-local-memory instruction to AGENTS.md (once)."""
    if not agents_md.is_file():
        return
    text = agents_md.read_text(encoding="utf-8")
    if _MEMORY_MARKER in text:
        return
    if not dry_run:
        sep = "" if text.endswith("\n") else "\n"
        agents_md.write_text(text + sep + _MEMORY_SECTION, encoding="utf-8")
    actions.append(f"add Memory section to {_rel(agents_md, root)}")


def _link_copilot(root: Path, *, actions: list[str], dry_run: bool) -> None:
    target = root / "AGENTS.md"
    if not target.exists():
        return
    link = root / ".github" / "copilot-instructions.md"
    if not dry_run:
        link.parent.mkdir(parents=True, exist_ok=True)
    _ensure_symlink(link, target, relative=True,
                    actions=actions, root=root, dry_run=dry_run)


def _link_shared_skills(root: Path, *, actions: list[str], dry_run: bool) -> None:
    """Expose the canonical skills (``.claude/skills``) via the tool-neutral
    ``.agents/skills`` path — at the root AND inside every project, so any agent
    working in a project dir finds the same shared skills.

    Root AGENTS.md / CLAUDE.md don't need per-project links: agents already
    inherit them by walking up the directory tree from the project folder.
    """
    canonical = root / ".claude" / "skills"
    if not canonical.is_dir():
        return
    # Root tool-neutral alias: .agents/skills -> .claude/skills
    _ensure_symlink(root / ".agents" / "skills", canonical, relative=True,
                    actions=actions, root=root, dry_run=dry_run)
    # Each project: both the Claude path and the tool-neutral path resolve to it.
    projects_root = root / "projects"
    if projects_root.is_dir():
        for pdir in sorted(projects_root.iterdir()):
            if not (pdir / "project.json").is_file():
                continue
            _ensure_symlink(pdir / ".claude" / "skills", canonical, relative=True,
                            actions=actions, root=root, dry_run=dry_run)
            _ensure_symlink(pdir / ".agents" / "skills", canonical, relative=True,
                            actions=actions, root=root, dry_run=dry_run)


def _ensure_memory_index(repo_mem: Path, *, actions: list[str],
                         root: Path, dry_run: bool) -> None:
    """Ensure the canonical memory dir exists + has a MEMORY.md (so git tracks it)."""
    if not dry_run:
        repo_mem.mkdir(parents=True, exist_ok=True)
    index = repo_mem / "MEMORY.md"
    if not index.exists():
        if not dry_run:
            index.write_text(_MEMORY_INDEX_STUB, encoding="utf-8")
        actions.append(f"create {_rel(index, root)}")


def _relocate_memory(claude_dir: Path, repo_dir: Path, *, actions: list[str],
                     root: Path, dry_run: bool) -> None:
    """Make ``repo_dir`` the canonical memory and ``claude_dir`` a symlink to it."""
    if not dry_run:
        repo_dir.mkdir(parents=True, exist_ok=True)
    # Already a symlink → ensure it points at the repo.
    if claude_dir.is_symlink():
        try:
            if claude_dir.resolve() == repo_dir.resolve():
                return
        except OSError:
            pass
        if not dry_run:
            claude_dir.unlink()
            claude_dir.symlink_to(repo_dir)  # absolute: crosses ~/.claude → repo
        actions.append(f"repoint {_rel(claude_dir, root)} → {_rel(repo_dir, root)}")
        return

    # Real dir → move its files into the repo (never overwrite an existing repo copy).
    if claude_dir.is_dir():
        moved = 0
        for f in sorted(claude_dir.iterdir()):
            dest = repo_dir / f.name
            if dest.exists():
                continue
            if not dry_run:
                shutil.move(str(f), str(dest))
            moved += 1
        if not dry_run:
            try:
                claude_dir.rmdir()
            except OSError:
                # Leftover collisions — preserve rather than lose data.
                shutil.move(str(claude_dir), str(claude_dir.with_name("memory.pre-sync")))
            claude_dir.symlink_to(repo_dir)
        actions.append(
            f"migrate {moved} file(s) {_rel(claude_dir, root)} → {_rel(repo_dir, root)}, symlink"
        )
        return

    # No claude dir yet → point it at the repo so future writes land in-repo.
    if not dry_run:
        claude_dir.parent.mkdir(parents=True, exist_ok=True)
        claude_dir.symlink_to(repo_dir)
    actions.append(f"link {_rel(claude_dir, root)} → {_rel(repo_dir, root)}")


def _write_adapter(dest: Path, name: str, rel_skill: str,
                   *, actions: list[str], root: Path, dry_run: bool) -> None:
    """Write a thin pointer adapter for Codex/Copilot.

    Idempotent: skips hand-written files, and skips generated files that are
    already up to date (so re-runs report no action).
    """
    body = (
        f"{GENERATED_MARK}\n"
        f"# {name}\n\n"
        f"Follow the instructions in `{rel_skill}` (relative to the repo root). "
        f"That file is the canonical definition of this capability; this is a thin "
        f"pointer so Codex / Copilot can invoke it too.\n"
    )
    if dest.exists():
        try:
            current = dest.read_text(encoding="utf-8")
        except OSError:
            current = ""
        first = current.splitlines()[:1]
        if not first or first[0] != GENERATED_MARK:
            return  # hand-written — leave it alone
        if current == body:
            return  # already current — no-op
    if not dry_run:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(body, encoding="utf-8")
    actions.append(f"write adapter {_rel(dest, root)} → {rel_skill}")


def _sync_skill_adapters(root: Path, *, actions: list[str], dry_run: bool) -> None:
    skills_dir = root / ".claude" / "skills"
    if not skills_dir.is_dir():
        return
    gh_prompts = root / ".github" / "prompts"
    codex_prompts = Path.home() / ".codex" / "prompts"
    for skill in sorted(skills_dir.iterdir()):
        if not (skill / "SKILL.md").is_file():
            continue
        name = skill.name
        rel_skill = f".claude/skills/{name}/SKILL.md"
        _write_adapter(gh_prompts / f"{name}.prompt.md", name, rel_skill,
                       actions=actions, root=root, dry_run=dry_run)
        _write_adapter(codex_prompts / f"{name}.md", name, rel_skill,
                       actions=actions, root=root, dry_run=dry_run)


def sync_all(root: Path, *, dry_run: bool = False) -> dict:
    """Run the full unification. Returns ``{actions, dry_run}``."""
    actions: list[str] = []

    # 1. Root instructions: AGENTS.md canonical + CLAUDE.md / copilot symlinks.
    _migrate_instructions(root, create_stub=True,
                          actions=actions, root=root, dry_run=dry_run)
    _ensure_memory_section(root / "AGENTS.md",
                           actions=actions, root=root, dry_run=dry_run)
    _link_copilot(root, actions=actions, dry_run=dry_run)

    # 2. Root memory: relocate FIRST (so a real MEMORY.md migrates intact), then
    #    ensure an index stub only if the dir ended up without one.
    repo_mem = paths.memory_dir(root)
    _relocate_memory(paths.claude_memory_dir(root), repo_mem,
                     actions=actions, root=root, dry_run=dry_run)
    _ensure_memory_index(repo_mem, actions=actions, root=root, dry_run=dry_run)

    # 3. Per-project: instructions (only where a CLAUDE.md exists) + memory (always,
    #    so future project sessions write memory in-repo too).
    projects_root = root / "projects"
    if projects_root.is_dir():
        for pdir in sorted(projects_root.iterdir()):
            if not (pdir / "project.json").is_file():
                continue
            _migrate_instructions(pdir, create_stub=False,
                                  actions=actions, root=root, dry_run=dry_run)
            proj_mem = paths.memory_dir(root, pdir.name)
            _relocate_memory(paths.claude_memory_dir(pdir), proj_mem,
                             actions=actions, root=root, dry_run=dry_run)
            _ensure_memory_index(proj_mem, actions=actions, root=root, dry_run=dry_run)

    # 4. Shared skills: canonical .claude/skills exposed via .agents/skills at
    #    the root and inside every project.
    _link_shared_skills(root, actions=actions, dry_run=dry_run)

    # 5. Skills: best-effort pointer adapters for Codex / Copilot.
    _sync_skill_adapters(root, actions=actions, dry_run=dry_run)

    return {"actions": actions, "dry_run": dry_run}
