# Configuration for go/adu.
# See go/adu-cfg for supported configuration properties and values.
# e.g. default_reviewers, ignored_updates, automerge_updates ...

version: 1

update_configs:
  - package_manager: java
    directory: /
    schedule:
      interval: weekly
    allowed_updates:
      - match:
          dependency_name: ligradle-python
          update_type: semver:minor
    automerged_updates:
      - match:
          dependency_name: ligradle-python
          update_type: semver:minor
    grouped_updates:
      - match:
          dependency_name: ligradle-python
          group: wildcards
    open_pull_requests_limit: 5
  - package_manager: python
    directory: /
    schedule:
      interval: weekly
    automerged_updates: []
    grouped_updates:
      - match:
          dependency_name: 'pypi:.*'
          group: 'pypi'
    open_pull_requests_limit: 5
