"""Read-only context checks and conservative removal of legacy Lab agent links.

Framework context now lives in the installed CLI and is supplied at launch.
No workspace instruction, skill, or memory files are created or rewritten.
"""
from __future__ import annotations

from datetime import datetime, timezone
import json
import os
from pathlib import Path
import shutil
import uuid

from lab import agent_context, naming, paths

GENERATED_MARK = '<!-- generated by `lab agents sync` — edit the canonical source instead -->'
NOTICE = 'Framework context is supplied at agent launch. Workspace instructions, skills, and memory are user-owned.'


def _scopes(root: Path) -> list[Path]:
    scopes = [root]
    directory = naming.workspaces_dir(root)
    if directory.is_dir() and not directory.is_symlink():
        scopes.extend(p for p in sorted(directory.iterdir())
                      if p.is_dir() and not p.is_symlink() and naming.workspace_metadata_file(p).is_file())
    return scopes


def _lexical(path: Path) -> str:
    return os.path.abspath(path)


def legacy_links(root: Path) -> list[dict[str, str]]:
    """Recognize exact old Lab layouts; never follow directory links or glob broadly.

    Real files, custom symlink targets, skill contents, settings and memory data
    are left intact. Matching paths/targets are also recorded before removal.
    """
    found = []
    root = root.resolve()
    for scope in _scopes(root):
        candidates = [
            (scope / 'CLAUDE.md', [scope / 'AGENTS.md', root / 'content/skills/workspace-CLAUDE.md']),
            (scope / '.github/copilot-instructions.md', [scope / 'AGENTS.md']),
            (scope / '.agents/skills', [root / '.claude/skills']),
        ]
        if scope != root:
            candidates.append((scope / '.claude/skills', [root / '.claude/skills']))
        candidates.append((paths.claude_memory_dir(scope), [scope / '.agents/memory']))
        for link, targets in candidates:
            # A parent may itself point outside the workspace. Never mutate it.
            anchor = scope if scope in link.parents else Path.home()
            if any(parent.is_symlink() for parent in link.parents if parent != anchor and anchor in parent.parents):
                continue
            if not link.is_symlink():
                continue
            target = os.readlink(link)
            if _lexical(link.parent / target) in {_lexical(t) for t in targets}:
                found.append({'path': str(link), 'target': target})
    return found


def detach(root: Path, *, dry_run: bool = False) -> dict:
    root = root.resolve()
    links = legacy_links(root)
    report = {'root': str(root), 'dry_run': dry_run, 'links': links, 'actions': [], 'errors': []}
    if dry_run:
        report['actions'] = [f"remove legacy link {link['path']} -> {link['target']}" for link in links]
        return report
    if not links:
        return report
    # This audit is client state, not a file in a vault or workspace.
    directory = paths.global_config_dir() / 'state' / 'agent-migrations'
    directory.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')
    audit = directory / f'{stamp}-{uuid.uuid4().hex[:8]}.json'
    report['audit'] = str(audit)
    audit.write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    for entry in links:
        link = Path(entry['path'])
        try:
            if not link.is_symlink() or os.readlink(link) != entry['target']:
                report['errors'].append(f'changed during migration; preserved {link}')
                continue
            link.unlink()
            report['actions'].append(f'removed legacy link {link}')
        except OSError as exc:
            report['errors'].append(f'{link}: {exc}')
    audit.write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    return report


def doctor_all(root: Path | None = None, *, include_cli: bool = True) -> dict:
    checks = [{'label': f'Lab context: {topic}', 'ok': agent_context.guide_path(topic).is_file(),
               'detail': str(agent_context.guide_path(topic))} for topic in agent_context.TOPICS]
    cli = [{'label': {'claude': 'Claude Code CLI', 'codex': 'Codex CLI', 'copilot': 'GitHub Copilot CLI'}[agent],
            'ok': bool(shutil.which(agent)), 'detail': shutil.which(agent) or 'not found'}
           for agent in agent_context.AGENTS] if include_cli else []
    return {'ok': all(row['ok'] for row in checks), 'checks': checks, 'cli': cli,
            'cli_ok': all(row['ok'] for row in cli) if include_cli else None,
            'notice': NOTICE, 'legacy_links': legacy_links(root) if root and root.is_dir() else []}


def sync_all(root: Path, *, dry_run: bool = False) -> dict:
    """Compatibility for old callers. Deliberately does not mutate any files."""
    return {'actions': [], 'dry_run': dry_run, 'notice': NOTICE,
            'context': doctor_all(root, include_cli=False)}


def sync_notebook_instructions(root: Path, *, dry_run: bool = False) -> dict:
    return sync_all(root, dry_run=dry_run)
