#!/bin/bash
set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
VENV="$DIR/venv"

echo "Creating venv..."
python3 -m venv "$VENV"

echo "Installing dependencies..."
"$VENV/bin/pip" install --upgrade pip -q
"$VENV/bin/pip" install -r "$DIR/requirements.txt" -q

# Generate a wrapper that binds ./download.py to the venv's python. The
# source shebang uses /usr/bin/env python3 so the repo is portable; this
# wrapper restores the "runs with the venv's python" guarantee without
# hardcoding an absolute path in the tracked files.
cat > "$DIR/darwin-backups" <<EOF
#!/bin/bash
# Auto-generated by setup.sh — do not edit; regenerated on each setup.
exec "$VENV/bin/python3" "$DIR/download.py" "\$@"
EOF
chmod +x "$DIR/darwin-backups" "$DIR/download.py" "$DIR/download-all.py"

echo ""
echo "Setup complete. Usage:"
echo "  ./darwin-backups /jcortes"
echo '  ./darwin-backups "https://darwin.prod.linkedin.com/ui/...?path=..."'
echo "  (or: venv/bin/python3 download.py <args>)"
